// Fetches the current Weeek OpenAPI spec from the official docs site
// (developers.weeek.net ships it as a Zudoku data chunk) and regenerates
// src/generated/operations.ts. Run: npm run update:openapi
import { mkdir, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import path from "node:path";

const DOCS = "https://developers.weeek.net";
const OUT_DIR = path.resolve("src/generated");
const CHUNK_FILE = path.join(OUT_DIR, "weeek-spec.mjs");
const OPS_FILE = path.join(OUT_DIR, "operations.ts");
const METHODS = ["get", "post", "put", "patch", "delete"];

// Operations covered by hand-written (curated) tools — kept out of the
// generated admin groups so there is exactly one way to do each thing.
const CURATED = new Set([
  // reads
  "get-profile", "get-workspace", "get-workspace-members", "get-projects", "get-tags",
  "get-tasks", "get-task", "get-task-comments", "get-attachment",
  // writes
  "create-task", "update-task", "complete-task", "uncomplete-task",
  "change-task-board", "change-task-board-column",
  "create-task-comment", "delete-task-comment",
  "add-assignees-to-task", "remove-assignees-from-task",
  "add-watchers-to-task", "remove-watchers-from-task",
]);

const fetchText = async (url) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
};

// 1. Locate the entry bundle.
const home = await fetchText(`${DOCS}/`);
const entryRel = home.match(/\/assets\/entry\.client-[A-Za-z0-9_-]+\.js/)?.[0];
if (!entryRel) throw new Error("entry.client chunk not found in docs HTML");
const entry = await fetchText(`${DOCS}${entryRel}`);

// 2. Locate the spec chunk it lazy-loads.
const specRel = entry.match(/\.\/weeek\.yaml-[A-Za-z0-9_-]+\.js/)?.[0];
if (!specRel) throw new Error("weeek.yaml chunk not found in entry bundle");
const specUrl = `${DOCS}/assets/${specRel.slice(2)}`;
console.error(`spec chunk: ${specUrl}`);

const specJs = await fetchText(specUrl);
await mkdir(OUT_DIR, { recursive: true });
await writeFile(CHUNK_FILE, specJs);

// 3. Import it as an ES module and pull the schema + slug map out.
const mod = await import(`${pathToFileURL(CHUNK_FILE).href}?v=${Date.now()}`);
const schema = mod.schema;
const slugs = mod.slugs ?? {};
if (!schema?.paths) throw new Error("chunk did not export an OpenAPI schema");

const typeOf = (s) => {
  if (!s) return "unknown";
  const t = s.type;
  if (Array.isArray(t)) return t.join("|");
  return typeof t === "string" ? t : "object";
};

// The docs site's slug map misses a couple of labels — fix them up so the
// generated tool names stay readable (weeek_board_column, weeek_funnel_statuses).
const SLUG_FIX = { boardcolumn: "board-column", funnelstatuses: "funnel-statuses" };

const operations = {};
const groups = new Map();
let total = 0;
let curatedCount = 0;

for (const [p, opsObj] of Object.entries(schema.paths)) {
  for (const [m, op] of Object.entries(opsObj)) {
    if (!METHODS.includes(m)) continue;
    total++;
    if (!op.operationId) throw new Error(`operation without operationId: ${m} ${p}`);

    const label = op.tags?.[0] ?? "Other";
    const rawSlug = slugs[label] ?? label.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const slug = SLUG_FIX[rawSlug] ?? rawSlug;
    const def = {
      id: op.operationId,
      method: m.toUpperCase(),
      path: p,
      summary: op.summary ?? "",
      tag: label,
      slug,
      pathParams: [],
      queryParams: [],
      bodyFields: [],
      hasBody: Boolean(op.requestBody),
    };
    for (const prm of op.parameters ?? []) {
      const param = { name: prm.name, type: typeOf(prm.schema), required: Boolean(prm.required) };
      if (Array.isArray(prm.schema?.enum)) param.enum = prm.schema.enum;
      (prm.in === "path" ? def.pathParams : def.queryParams).push(param);
    }
    const bodySchema = op.requestBody?.content?.["application/json"]?.schema;
    const requiredBody = new Set(bodySchema?.required ?? []);
    for (const [name, fs] of Object.entries(bodySchema?.properties ?? {})) {
      const f = { name, type: typeOf(fs), required: requiredBody.has(name) };
      if (Array.isArray(fs.enum)) f.enum = fs.enum;
      def.bodyFields.push(f);
    }

    operations[op.operationId] = def;
    if (CURATED.has(op.operationId)) {
      curatedCount++;
      continue; // not part of generated groups
    }
    if (!groups.has(label)) groups.set(label, { slug, label, opIds: [] });
    groups.get(label).opIds.push(op.operationId);
  }
}

const groupList = [...groups.values()].sort((a, b) => a.slug.localeCompare(b.slug));

const header = [
  `// @generated by scripts/update-openapi.mjs on ${new Date().toISOString()}`,
  `// Source: ${specUrl}`,
  `// Do not edit by hand — run: npm run update:openapi`,
  ``,
  `export type ParamDef = { name: string; type: string; required: boolean; enum?: (string | number)[] };`,
  `export type OpDef = {`,
  `  id: string;`,
  `  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";`,
  `  path: string;`,
  `  summary: string;`,
  `  tag: string;`,
  `  slug: string;`,
  `  pathParams: ParamDef[];`,
  `  queryParams: ParamDef[];`,
  `  bodyFields: ParamDef[];`,
  `  hasBody: boolean;`,
  `};`,
  `export type GroupDef = { slug: string; label: string; opIds: string[] };`,
  ``,
].join("\n");

const body = [
  `export const SPEC_URL = ${JSON.stringify(specUrl)};`,
  `export const SPEC_TITLE = ${JSON.stringify(schema.info?.title ?? "")};`,
  `export const OPERATIONS: Record<string, OpDef> = ${JSON.stringify(operations)};`,
  `export const GROUPS: GroupDef[] = ${JSON.stringify(groupList, null, 2)};`,
  ``,
].join("\n");

await writeFile(OPS_FILE, header + body);
console.error(
  `total operations: ${total}; in admin groups: ${total - curatedCount}; curated (excluded): ${curatedCount}; groups: ${groupList.length}`,
);
